"""create folders table

Revision ID: b83bb99e4265
Revises: b54e5d01621c
Create Date: 2024-08-24 18:25:34.786199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83bb99e4265'
down_revision = 'b54e5d01621c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(
                        length=20), nullable=False),
                    sa.Column('password', sa.Text(), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )

    op.create_table('folders',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('folder_name', sa.Text(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('summaries',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('original_url', sa.String(
                        length=255), nullable=False),
                    sa.Column('summary_text', sa.Text(), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('folder_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('saved_summaries',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('summary_id', sa.Integer(), nullable=False),
                    sa.Column('folder_name', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['summary_id'], ['summaries.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_summaries')
    op.drop_table('summaries')
    op.drop_table('folders')
    op.drop_table('users')
    # ### end Alembic commands ###
