"""Add first_name and last_name to users

Revision ID: cdf0a96b3278
Revises: 34ffd871df89
Create Date: 2023-11-15 22:30:46.515590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf0a96b3278'
down_revision = '34ffd871df89'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('users',
                    sa.Column('id', sa.Integer(),
                              nullable=False, primary_key=True),
                    sa.Column('username', sa.String(
                        length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=50), nullable=False),
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
